#ifndef _LCOM_I8042_H_
#define _LCOM_I8042_H_

#include <lcom/lcf.h>

// IRQ LINES
#define KEYBOARD_IRQ 1
#define MOUSE_IRQ 12

// KBC REGISTERS
#define KBC_ST_REG 0x64
#define KBC_CMD_REG 0x64
#define KBC_IN_BUF 0x60
#define KBC_OUT_BUF 0x60

// KBC COMMANDS
#define KBC_READ_CMD 0x20
#define KBC_WRITE_CMD 0x60
#define ENABLE_INTERRUPTS BIT(0)

// STATUS BYTE
#define KBC_IBF BIT(1)
#define KBC_OBF BIT(0)
#define KBC_PARITY BIT(7)
#define KBC_TIMEOUT BIT(6)
#define KBC_AUX BIT(5)

// MOUSE COMMANDS
// DEVEM SER PASSADOS VIA ARGUMENTO DO COMANDO 0xD4
// (ESCRITOS NO IN_BUF 0X60) OU LIDOS (OUT_BUF 0x60)
#define SET_STREAM_MODE 0xEA
#define ENABLE_DATA_REPORT 0xF4
#define DISABLE_DATA_REPORT 0xF5
#define ACK 0xFA
#define NACK 0XFE
#define ERROR 0xFC
#define MOUSE_WRITE_BYTE 0xD4

// MOUSE PACKET BYTE 1 BITS
#define MOUSE_LB BIT(0)
#define MOUSE_RB BIT(1)
#define MOUSE_MB BIT(2)
#define FIRST_BYTE BIT(3)
#define MSB_X_DELTA BIT(4)
#define MSB_Y_DELTA BIT(5)
#define MOUSE_X_OVFL BIT(6)
#define MOUSE_Y_OVFL BIT(7)

// DELAY
#define DELAY_US 20000

// LAB3
#define BREAKCODE BIT(7)

#define TWO_BYTES 0xE0
#define ESC_BREAK 0x81
#define ENTER_BREAK (0x1C | BREAKCODE)
#define MINUS_BREAK 0x0C | BREAKCODE
#define PLUS_BREAK 0x0D | BREAKCODE
#define SPACE_BREAK 0x0E | BREAKCODE

#define ZERO_BREAK 0x0B | BREAKCODE
#define ONE_BREAK 0x02 | BREAKCODE
#define TWO_BREAK 0x03 | BREAKCODE
#define THREE_BREAK 0x04 | BREAKCODE
#define FOUR_BREAK 0x05 | BREAKCODE
#define FIVE_BREAK 0x06 | BREAKCODE
#define SIX_BREAK 0x07 | BREAKCODE
#define SEVEN_BREAK 0x08 | BREAKCODE
#define EIGHT_BREAK 0x09 | BREAKCODE
#define NINE_BREAK 0x0A | BREAKCODE

#define A_BREAK 0x1E | BREAKCODE
#define B_BREAK 0x30 | BREAKCODE
#define C_BREAK 0x2E | BREAKCODE
#define D_BREAK 0x20 | BREAKCODE
#define E_BREAK 0x12 | BREAKCODE
#define F_BREAK 0x21 | BREAKCODE
#define G_BREAK 0x22 | BREAKCODE
#define H_BREAK 0x23 | BREAKCODE
#define I_BREAK 0x17 | BREAKCODE
#define J_BREAK 0x24 | BREAKCODE
#define K_BREAK 0x25 | BREAKCODE
#define L_BREAK 0x26 | BREAKCODE
#define M_BREAK 0x32 | BREAKCODE
#define N_BREAK 0x31 | BREAKCODE
#define O_BREAK 0x18 | BREAKCODE
#define P_BREAK 0x19 | BREAKCODE
#define Q_BREAK 0x10 | BREAKCODE
#define R_BREAK 0x13 | BREAKCODE
#define S_BREAK 0x1F | BREAKCODE
#define T_BREAK 0x14 | BREAKCODE
#define U_BREAK 0x16 | BREAKCODE
#define V_BREAK 0x2F | BREAKCODE
#define W_BREAK 0x11 | BREAKCODE
#define X_BREAK 0x2D | BREAKCODE
#define Y_BREAK 0x15 | BREAKCODE
#define Z_BREAK 0x2C | BREAKCODE

#define ARROW_UP_BREAK (0x48 | BREAKCODE)
#define ARROW_DOWN_BREAK (0x50 | BREAKCODE)
#define ARROW_LEFT_BREAK (0x4B | BREAKCODE)
#define ARROW_RIGHT_BREAK (0x4D | BREAKCODE)

#endif
